name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Aliyun Container Registry
        run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALIYUN_REGISTRY }} -u "${{ secrets.ALIYUN_REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_REGISTRY }}/starfishes/nonebot-cli:${{ github.event.inputs.tag || 'latest' }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/starfishes/nonebot-cli:${{ github.event.inputs.tag || 'latest' }}
